# Generated by Django 4.0.3 on 2022-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='logoUrl',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
