# Generated by Django 4.0.3 on 2022-05-01 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_profile_alter_comment_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='chieftain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
